import Link from "next/link";
import type { Metadata } from "next";
import { DEMO_NETWORKS } from "@/lib/network/demo";

export const metadata: Metadata = {
  title: "Visual Social Layer for Podcast Networks",
  description:
    "Episodes in, a branded weekly distribution package out — formatted for LinkedIn, Instagram and X, across a network's full show roster.",
};

const NAV = [
  { href: "/network", label: "The system" },
  { href: "/network/studio", label: "Studio" },
];

export default function NetworkLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="min-h-screen bg-[#08080a] text-white/90 antialiased">
      <header className="sticky top-0 z-50 border-b border-white/10 bg-[#08080a]/85 backdrop-blur-md">
        <div className="mx-auto flex h-14 max-w-7xl items-center gap-6 px-5">
          <Link href="/network" className="flex items-center gap-2.5 shrink-0">
            <span className="grid h-7 w-7 place-items-center rounded-md bg-white text-[11px] font-black text-black">
              HV
            </span>
            <span className="text-[13px] font-semibold tracking-tight">
              Network Layer
            </span>
          </Link>

          <nav className="flex items-center gap-1 text-[13px]">
            {NAV.map((item) => (
              <Link
                key={item.href}
                href={item.href}
                className="rounded-md px-2.5 py-1.5 text-white/55 transition-colors hover:bg-white/5 hover:text-white"
              >
                {item.label}
              </Link>
            ))}
          </nav>

          <div className="ml-auto flex items-center gap-1 text-[13px]">
            <span className="hidden text-white/30 sm:inline">Proposals:</span>
            {DEMO_NETWORKS.map((n) => (
              <Link
                key={n.slug}
                href={`/network/proposal/${n.slug}`}
                className="rounded-md px-2 py-1.5 text-white/55 transition-colors hover:bg-white/5 hover:text-white"
              >
                {n.name.split(" ")[0]}
              </Link>
            ))}
          </div>
        </div>
      </header>

      {children}

      <footer className="border-t border-white/10 px-5 py-10">
        <div className="mx-auto flex max-w-7xl flex-col gap-2 text-[12px] text-white/35 sm:flex-row sm:items-center sm:justify-between">
          <p>A white-label visual distribution system for podcast networks.</p>
          <p>Every asset on this site was generated by the pipeline, not designed by hand.</p>
        </div>
      </footer>
    </div>
  );
}
